read_userdb_error: Because this function didn't handle last_fail = undefined, the whole sipuserdb_file_backend server would crash on parse errors, eventually bringing the whole system down. Fix bug and add test case.
Problem noted by Jakob Schlyter.


git-svn-id: svn://anonsvn.it.su.se/yxa/trunk@1041 e454d3dc-12ff-0310-9b8b-94264392205f